import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav";
import Footer from "@/components/Footer";
import Providers from "./providers";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={inter.className}>
   
        <Nav />
  
        <main className="max-w-[1440px] mx-20 px-4 mt-10 rounded-xl max-sm:mx-4 max-md:mx-14 border border-pink-950">

       <Providers>{children}</Providers> 
        </main>
        <Footer/>
        </body>
    </html>
  );
}
